### ISSUE TITLE
stuck after res

### ISSUE THREAD

**Issue by kernel-dc** [Lambda11/instant-revive#1]
if i die with a debuff, lets say fear or something i can't move after res even if i get hit.

**Comment by Owyn** [comment]
that's interesting, I don't really see how that can happen... do you know any places or dungeons where to test that kind of death?

**Comment by proxyuser15** [comment]
BRE 2nd boss (in EU)

**Comment by Owyn** [comment]
no way to test that for those outside EU tho 🤔

**Comment by Lambda11** [comment]
@kernel-dc @proxyuser15 
Just pushed a possible fix, please test and say if it helps and writes something in the proxy chat when you die under a fear effect
